# PYTHON PROGRAM TO FIND THE SECOND LARGEST NUMBER N A LIST

listValue = [20,67,74,22,88,45,99]

# HERE SORTIG THE LIST BY THE SORT FUNCTION
listValue.sort()


# HERE NOW DISPLAYING THE SECOND LARGEST NUMBER OF THE LIST
print("THE SECOND LARGEST ELEMENT OF THE LIST IS ",listValue[-2])
